name: Python Package

on: [push]

jobs:
  build:
    name: Build and Test (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -el {0}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.10", "3.9", "3.8"]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
      - name: Install Conda Dependencies
        run: |
          conda install -y -c conda-forge xarray cfgrib dask netCDF4 bottleneck scipy
      - name: Install Pip Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          python -m pip install -r requirements-dev.txt
      - name: Isort
        run: |
          python -m isort --check ./
      - name: Black
        run: |
          python -m black --check ./
      - name: Flake8
        run: |
          python -m flake8 . --count --show-source --statistics
      - name: Pytest
        run: |
          python -m pip install .
          python -m pytest
      - name: Build
        run: |
          python -m pip install --upgrade build
          python -m build
